### ISSUE TITLE
options.go seems needlessly complex

### ISSUE THREAD

**Issue by ijt** [opencensus-integrations/ocsql#6]
Why does it have all these functions that only fill out individual fields of the TraceOptions struct? Why not use the built-in Go syntax for struct literals instead?

**Comment by odeke-em** [comment]
@ijt those are options which are a Go idiomatic pattern for declaring what you would like your initialization to look like. Passing in a struct for initialization could work but then means that users can then dynamically modify the internals and then you need unnecessary locks, which perhaps isn't what we'd want.

You can find more about them at https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis 
and for an example that might be closer to you at Google, here is a bunch of Google API client options https://godoc.org/google.golang.org/api/option
and in gRPC please see https://godoc.org/google.golang.org/grpc#DialOption and search for the prefix `func With`

/cc @basvanbeek @zombiezen

**Comment by basvanbeek** [comment]
People needing to use structs / explicit parameters for config options can do so like this:

```go
options := ocsql.TraceOptions{RowsClose: true}
driverName, err := ocsql.Register("driver", ocsql.WithOptions(options))
```

**Comment by ijt** [comment]
Passing a config struct by value should not require any locking. If you pass a pointer to it then there could be some problem, but that's not necessary.

Anyway, thanks for explaining. The post by Dave Cheney got me thinking, and I'll probably try using this idea.

**Comment by odeke-em** [comment]
>should not require any locking. If you pass a pointer to it then there could be some problem.

In deed, so sorry if am preaching to the choir but your last sentence captured the essence of my caution about locking which is that if you are passing a struct with many fields, it is useful to pass it by reference i.e. as a pointer, in order to save on memory wastage from copying -- in most cases such as even this, as you can see there are many fields in the struct.

 >Anyway, thanks for explaining. The post by Dave Cheney got me thinking, and I'll probably try using this idea.

Anytime, we are quite excited to see your work and see your project using ocsql and OpenCensus as well. It is a pleasure to collaborate with y'all! Great to hear you liked the reference post.
